rollup 进行 dist 打包的能力
ice-lab/component-next pull request #5
Opened 2022-02-25 04:13 UTC by maoxiaoke

2022-02-28 07:18 UTC, imsobear requested changes

2022-02-28 07:18 UTC, imsobear commented on packages/component-next/src/build.ts
>    return Promise.all(
为什么需要 promise 的写法

2022-02-28 07:18 UTC, imsobear commented on packages/plugin-component/src/index.ts
> +    },
这两个参数还需要在这里指定吗？

2022-02-28 07:40 UTC, maoxiaoke commented on packages/component-next/src/build.ts
>    return Promise.all(
任务都是异步函数
希望保持任务并发执行
统一通过 try... catch 进行 catch

2022-02-28 07:44 UTC, maoxiaoke commented on packages/component-next/src/helpers/getPlugins.ts
> +      dtsPlugin(userConfig.declaration),
两个功能：

1. ts 生成 d.ts
2. js 生成 d.ts

都是这个插件来承载的

2022-02-28 07:48 UTC, maoxiaoke commented on packages/component-next/src/helpers/normalizeRollupConfig.ts
> +  }
项目不存在 src/index.js 文件

2022-02-28 08:13 UTC, maoxiaoke commented on packages/component-next/src/cli.ts
> +import componentService from './index';
是的，build-scripts 已经迁移成 pure esm package 了

2022-02-28 08:18 UTC, maoxiaoke commented on packages/plugin-component/src/index.ts
> +    },
service 并不区分 es/lib 两类

2022-02-28 08:26 UTC, maoxiaoke commented on packages/component-next/src/helpers/mergeConfigOptions.ts
> +  }
bundle 任务默认不执行，merge 这块是不是也应该尽量分开。rollupPlugins 是 transform & bundle 都消费的。

2022-02-28 08:28 UTC, imsobear commented on packages/component-next/src/helpers/normalizeRollupConfig.ts
> +  }
不存在的的话表现是怎么样的？这个 return; 是看不出来的。

2022-02-28 08:30 UTC, imsobear commented on packages/component-next/src/cli.ts
> +import componentService from './index';
那这里应该是 ./index.js 吧？tsconfig 是不是没改？改了的话不加 .js 会报错

2022-02-28 08:33 UTC, imsobear commented on packages/component-next/src/helpers/getPlugins.ts
> +      dtsPlugin(userConfig.declaration),
declaration 我看默认是 true，但是我记得之前 js 项目开启这个是有副作用的。所以是否考虑：

- ts 永远都生成 d.ts （这个也符合认知吧，没见过什么场景需要关闭）
- 这个选项名优化下，仅表示 js 项目是否生成 d.ts，默认是 false

2022-02-28 08:41 UTC, imsobear commented on packages/component-next/src/helpers/normalizeRollupConfig.ts
> +  }
打了个 error 日志，但是后续会怎么样？进程正常还是退出？没处理明白

2022-02-28 08:44 UTC, imsobear commented on packages/component-next/src/helpers/getSwcConfig.ts
> +};
有时候要接受代码冗余，不是所有的地方都要抽象，否则代码可读性会降低很多。这个地方你可以自己判断下，我说的这个问题是整体上有点抽象过度，不是针对这几行代码。

2022-02-28 08:46 UTC, imsobear commented on packages/component-next/src/helpers/mergeConfigOptions.ts
> +  }
感觉并不影响吧，我是感觉现在代码有点太碎了，阅读起来不是很过瘾。

2022-02-28 08:48 UTC, imsobear commented on packages/component-next/src/build.ts
>      await buildAll(extendsRollupConfigsArrs, context);
这里我觉得就别 map 了，任务类型都是可枚举的，提取出来执行就好了，registerTask 那里传参数的问题也就一起解决了。

2022-02-28 08:49 UTC, imsobear commented on packages/component-next/src/build.ts
> +    consola.error('CONFIG', errMsg);
这种是想做什么还是要交代清楚的，不然用户会懵逼的

2022-02-28 08:51 UTC, maoxiaoke commented on packages/component-next/src/helpers/getPlugins.ts
> +      dtsPlugin(userConfig.declaration),
现在这个配置是这样的：

declaration: true // ts -> d.ts 开启

declaration: {
  js: true // ts & js -> d.ts 开启
}

2022-02-28 11:02 UTC, maoxiaoke commented on packages/component-next/src/cli.ts
> +import componentService from './index';
done

2022-03-01 03:45 UTC, maoxiaoke commented on packages/component-next/src/helpers/getSwcConfig.ts
> +};
done

2022-03-01 03:45 UTC, maoxiaoke commented on packages/plugin-component/src/index.ts
> +    },
done

2022-03-01 03:46 UTC, maoxiaoke commented on packages/component-next/src/helpers/getPlugins.ts
> +      dtsPlugin(userConfig.declaration),
移除了这个配置，

transform 默认是 ts -> .d.ts，除非开启 generateTypesForJs

bundle 默认不开启

2022-03-01 07:00 UTC, imsobear approved these changes

2022-03-01 09:17 UTC, merged